wx:
  appid: wx6464862cb44f9f71
  secret: 97466ec125a4ee8bf7193818906f547e
  templateId:
  url: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&grant_type=authorization_code&js_code=

spring:
  application:
    name: RedTour
  datasource:
    username: root
    password: Qingyuan@666
    url: jdbc:mysql://8.140.10.241:3306/redtour?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.140.10.241
    password: Qingyuan@666

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qingyuan.redtour.pojo

logging:
  file:
    name: ./a-redtour/redtour.log
